=== DenisPan007/MultiThreating_Trip/src/test/resources/BusesXsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/buses"
        xmlns:tns="http://www.example.com/buses"
        elementFormDefault="qualified">
    <element name="buses">
        <complexType>
            <sequence>
                <element name="bus"
                         type="tns:Bus"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Bus">
        <all>
            <element name="id" type="positiveInteger"/>
            <element name="capacity" type="positiveInteger"/>
        </all>
    </complexType>
</schema>

=== DenisPan007/MultiThreating_Trip/src/test/resources/Buses.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<buses xmlns="http://www.example.com/buses"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/buses BusesXsd.xsd">
    <bus>
        <id>1</id>
        <capacity>5</capacity>
    </bus>
    <bus>
        <id>2</id>
        <capacity>4</capacity>
    </bus>
    <bus>
        <id>3</id>
        <capacity>3</capacity>
    </bus>

</buses>
