=== DenisPan007/MultiThreating_Trip/src/test/resources/PassengersXsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/passengers"
        xmlns:tns="http://www.example.com/passengers"
        elementFormDefault="qualified">
    <element name="passengers">
        <complexType>
            <sequence>
                <element name="passenger"
                         type="tns:Passenger"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Passenger">
        <all>
            <element name="name" type="string"/>
            <element name="destination" type="positiveInteger"/>
        </all>
    </complexType>
</schema>

=== DenisPan007/MultiThreating_Trip/src/test/resources/Passengers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<passengers xmlns="http://www.example.com/passengers"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.example.com/passengers PassengersXsd.xsd">
    <passenger>
        <name>Den1</name>
        <destination>2</destination>
    </passenger>
    <passenger>
        <name>Den2</name>
        <destination>3</destination>
    </passenger>
    <passenger>
        <name>Den3</name>
        <destination>4</destination>
    </passenger>

</passengers>
