=== DenisPan007/MultiThreating_Trip/src/test/resources/RoutesXsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/routes"
        xmlns:tns="http://www.example.com/routes"
        elementFormDefault="qualified">
    <element name="routes">
        <complexType>
            <sequence>
                <element name="route"
                         type="tns:Route"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Route">
        <all>
            <element name="number" type="positiveInteger"/>
            <element name="busStops"
                     type="tns:BusStops"/>
        </all>
    </complexType>
    <complexType name="BusStops">
    <sequence>
        <element name="stop" type="positiveInteger" maxOccurs="unbounded"/>
    </sequence>
    </complexType>
</schema>

=== DenisPan007/MultiThreating_Trip/src/test/resources/Routes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<routes xmlns="http://www.example.com/routes"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.com/routes RoutesXsd.xsd">
    <route>
        <number>1</number>
        <busStops>
            <stop>1</stop>
            <stop>2</stop>
            <stop>3</stop>
            <stop>4</stop>
        </busStops>
    </route>
    <route>
        <number>2</number>
        <busStops>
            <stop>4</stop>
            <stop>3</stop>
            <stop>2</stop>
            <stop>1</stop>
        </busStops>
    </route>
    <route>
        <number>3</number>
        <busStops>
            <stop>1</stop>
            <stop>3</stop>
            <stop>4</stop>
            <stop>2</stop>
        </busStops>
    </route>

</routes>
